num_context_features: 288
latent_dim: 128
kernel_size: 5
num_resnet_blocks: 6
hidden_dim: 64
num_hidden_layers: 4
num_target_features: 1
context_lat_index: 19
context_long_index: 20
target_lat_index: 0
target_long_index: 1